// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/perses/spec/go/datasource/proxy/cloudwatch

package cloudwatch

import "github.com/perses/spec/cue/datasource/proxy"

// Config is the configuration of the CloudWatch proxy.
// It never contains AWS credentials: the Perses server signs the requests with its own identity,
// optionally assuming the role defined here.
#Config: _

// Proxy is the CloudWatch proxy definition proposed in Perses.
// In case you are defining a datasource that will work with the Perses backend, then you will need to use this definition.
#Proxy: proxy.#Proxy

#ProxyKindName: "cloudwatchproxy"
