// Copyright The Perses Authors
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// NB: This file complements the cloudwatch_go_gen.cue file generated by
// `cue get go` to add the missing constraints lost in the translation
// process. This should no longer be needed at some point hopefully, but for
// the moment, because of a technical limitation in the CUE translation
// process, a top-value (= "any") gets generated instead of a proper def for
// any type that defines a custom UnmarshallJSON or UnmarshallYAML.
// For more info see https://github.com/cue-lang/cue/issues/2466.

package cloudwatch

import (
	"github.com/perses/spec/cue/datasource/proxy"
)

#Config: {
	// region is the AWS region of the CloudWatch API, for example "us-east-1".
	region: string & =~"^[a-z]{2}(-[a-z]+)+-[0-9]{1,2}$" @go(Region)
	// roleArn is the ARN of the IAM role the Perses server assumes to query CloudWatch.
	// When it is empty, the server uses its own AWS identity directly.
	roleArn?: string & =~"^arn:aws(-[a-z]+)*:iam::[0-9]{12}:role/[A-Za-z0-9+=,.@_/-]{1,576}$" @go(RoleARN)
	// externalIdSecret is the name of the secret holding the external ID used to assume the role.
	// The external ID is stored in the authorization credentials of the secret.
	// It can only be set together with roleArn.
	externalIdSecret?: string @go(ExternalIDSecret)
	if externalIdSecret != _|_ {
		roleArn!: string
	}
}

#Proxy: proxy.#Proxy & {
	kind: "CloudWatchProxy" @go(Kind)
	spec: #Config           @go(Spec)
}
